spring:
  application:
    name: public-api
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000


logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    org.hibernate: WARN

server:
  port: ${PUBLIC_PORT:2000}