version: '3'

services:

  catalogue:
    build: ./catalogue
    command: java -jar service-register-1.0.0.jar
    depends_on:
    - db
    image: java:8
    volumes:
    - ./service-register/target:/app
    working_dir: /app

  db:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'bees_commerce'
    image: mysql:8.0.13
    ports:
    - "3306:3306"

  register:
    command: java -jar service-register-1.0.0.jar
    image: java:8
    ports:
    - "8761:8761"
    volumes:
    - ./service-register/target:/app
    working_dir: /app
