version: '3'

services:

  register:
    command: java -jar service-register.jar
    environment:
      DISCOVERY_PORT: 8761
    image: java:8
    ports:
      - "8761:8761"
    volumes:
      - ./service-register/target:/app
    working_dir: /app

  database:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
      MYSQL_DATABASE: 'bees_commerce'
    image: mysql:5
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  fcp:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
      MYSQL_DATABASE: 'bees_commerce'
    image: mysql:5
    ports:
      - "3307:3306"

  catalogue:
    command: java -jar products.jar
    depends_on:
      - register
      - database
    environment:
      DATABASE_HOST: 'database'
      DATABASE_PORT: '3306'
      DATABASE_USER: 'dbuser'
      DATABASE_PASS: 'dbpass'
      DATABASE_NAME: 'bees_commerce'
      DISCOVERY_SERVER: 'http://register:8761/eureka'
    image: java:8
    volumes:
      - ./products/target:/app
    working_dir: /app

  search:
    command: java -jar search.jar
    depends_on:
      - register
    environment:
      DISCOVERY_SERVER: 'http://register:8761/eureka'
      LUCENE_HOME: /lucene/index
    image: java:8
    volumes:
      - ./search/target:/app
      - search_index:/lucene
    working_dir: /app

  public-api:
    command: java -jar public-api.jar
    depends_on:
      - register
    environment:
      DISCOVERY_SERVER: 'http://register:8761/eureka'
      PUBLIC_PORT: 2000
    image: java:8
    ports:
      - '2000:2000'
    volumes:
      - ./public-api/target:/app
    working_dir: /app

volumes:
  database_data:
  search_index: