version: '3'

services:

  register:
    command: java -jar service-register.jar
    environment:
      DISCOVERY_PORT: 8761
    image: java:8
    ports:
      - "8761:8761"
    volumes:
      - ./service-register/target:/app
    working_dir: /app

  database:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
      MYSQL_DATABASE: 'bees_commerce'
    image: mysql:5
    ports:
      - "3306:3306"

  catalogue:
    build: ./catalogue
    command: java -jar catalogue.jar
    depends_on:
      - register
      - database
    environment:
      DATABASE_HOST: 'database'
      DATABASE_PORT: '3306'
      DATABASE_USER: 'dbuser'
      DATABASE_PASS: 'dbpass'
      DATABASE_NAME: 'bees_commerce'
      DISCOVERY_SERVER: 'http://register:8761/eureka'
    image: java:8
    volumes:
      - ./catalogue/target:/app
    working_dir: /app
