/**
 * Autogenerated by Thrift Compiler (0.9.1)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.beesden.commerce.common.model.search;

import lombok.Data;

import java.util.List;
import java.util.Map;

@Data
public class SearchResult {

	private String id;
	private String title;
	private Map<String, List<String>> metadata;

}

