/**
 * Autogenerated by Thrift Compiler (0.9.1)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.beesden.commerce.common.model.search;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.beesden.commerce.common.model.EntityReference;
import org.beesden.commerce.common.model.EntityType;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SearchDocument {

    private EntityReference entity;
    private String title;
    private Map<String, Set<String>> facets = new HashMap<>();

    public SearchDocument(EntityType type, String id) {
        this.entity = new EntityReference(type, id);
    }

}

