/**
 * Autogenerated by Thrift Compiler (0.9.1)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.beesden.common.model.search;

import lombok.Data;
import org.beesden.common.model.PagedResponse;

import java.util.Map;

@Data
public class SearchResultWrapper extends PagedResponse<SearchResult> {

	private Map<String, Map<String, Integer>> facets;

}

