/**
 * Autogenerated by Thrift Compiler (0.9.1)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package org.beesden.common.model.search;

import lombok.Data;
import org.beesden.common.model.EntityReference;

import java.util.Map;
import java.util.Set;

@Data
public class SearchDocument {

	private EntityReference entity;
	private String title;
	private Map<String, Set<String>> facets;

}

