spring:
  application:
    name: search-client

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN

lucene:
  directory: ${LUCENE_HOME:./lucene}

server:
  port: 0
